# -*- coding: utf-8 -*-
"""Rating_chess.com.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvQLsqWlrUBcfC5ix6NlBHioN0xVmwF4
"""

import json
import requests

# Make a request to the API
username = "Sayak_K"
response = requests.get(f"https://www.chess.com/callback/user/popup/{username}")
data = response.json()

# Pretty print the JSON data
print(json.dumps(data, indent=4))

import json
import requests

# Make a request to the API
username = "Sayak_K"
response = requests.get(f"https://www.chess.com/callback/user/popup/{username}")
data = response.json()

# Extract the required values
rating_1 = int(data["bestRating"])
rating_type_1 = data["bestRatingType"].upper()
puzzle_score_1 = int(data["topPuzzleRushScore"])
puzzle_type_1 = data["topPuzzleRushScoreType"].upper()

# Store the extracted values in capital letters and big size format
rating = rating_1
rating_type = rating_type_1
puzzle_score = puzzle_score_1
puzzle_type = puzzle_type_1

# Print the extracted values (optional)
print("Best Rating:", rating)
print("Best Rating Type:", rating_type)
print("Top Puzzle Rush Score:", puzzle_score)
print("Top Puzzle Rush Score Type:", puzzle_type)