name: Update Readme ascii graph and workflow with random cron interval
on:
  push:
    branches: 
      - master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
      - cron: "0 */1 * * *"
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate plot.png
        run: python generate_plot.py

      - name: Upload plot.png as artifact
        uses: actions/upload-artifact@v4
        with:
          name: plot
          path: assets/plot.png
          overwrite: true

      - name: Download plot.png as artifact
        uses: actions/download-artifact@v4
        with:
         name: plot
         path: assets
      - name: Display structure of downloaded files
        run: ls -R assets

      - name: Configure Git
        run: |
          git config --global user.name "SayakKDutta"
          git config --global user.email "sayak.kr.dutta1@gmail.com"
      - name: Pull changes from remote
        run: git pull origin main --ff-only
      - name: Add changes
        run: git add assets
      - name: Commit changes
        run: git commit -m "Update assets folder with downloaded artifact" --allow-empty
      - name: Push changes
        run: git push --force


      - name: Update README
        run: |
          currentDate=$(TZ=India/Kolkata date)
          printf "\nChart last updated - ${currentDate}" >> README.md
          
      - name: Commit changes
        if: ${{ failure() }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: SayakKDutta
          author_email: sayak.kr.dutta1@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml assets/updated_plot.png"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
