name: Update Readme ascii graph and workflow with random cron interval
on:
  push:
    branches: 
      - master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: "*/1 * * * *"
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate plot.png
        run: python generate_plot.py

      - name: Upload plot.png as artifact
        uses: actions/upload-artifact@v2
        with:
          name: plot
          path: assets/plot.png

      - name: Move plot.png to assets folder
        run: mv $GITHUB_WORKSPACE/assets/plot.png $GITHUB_WORKSPACE/assets/plot.png

      - name: Update README
        run: |
          currentDate=$(TZ=India/Kolkata date)
          printf "\nChart last updated - ${currentDate}" >> README.md

      - name: Commit changes
        if: ${{ failure() }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: SayakKDutta
          author_email: sayak.kr.dutta1@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
