name: Update Readme with Chess Rating Plot
on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ratings-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run generate_plot.py
        run: python generate_plot.py

      - name: Update README with plot
        run: |
          currentDate=$(date +'%Y-%m-%d %H:%M:%S')
          printf "\n![Chess Rating Plot](plot.png)\n\nPlot last updated - ${currentDate}" >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md plot.png
          git commit -m "Update README with Chess Rating Plot"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
