name: Update plot 1
on:
  push:
    branches: master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: "0 */5 * * *"
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_TOKEN_1 }}
        name: Setup Python

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
        name: Install dependencies

      - name: Install Python dependencies
        run: |
          pip install -i https://pypi.org/simple asciichartpy==1.5.24 certifi==2022.12.7 chardet==3.0.4 deprecated==1.2.10 idna==2.10 pygithub==1.51 pyjwt==2.4.0 requests==2.26.0 urllib3==1.26.5 wrapt==1.12.1 matplotlib

      
      - name: Create Chart
        run: python codes/generate_plot.py > plot.png

      - name: Embed Chart in README
        run: |
          currentDate=$(date +'%Y-%m-%d %H:%M:%S')
          printf "\n![Chess Rating Plot](plot.png)\n\nChart last updated - ${currentDate}" >> README.md

      - name: Update workflow yaml file
        run: |
          python codes/generate_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"
          cp rating-yaml.txt .github/workflows/rating-chart.yml

      - name: Commit changes
        id: changed
        run: git diff --exit-code
        continue-on-error: true

      - name: Push changes
        if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Sayak Kumar Dutta
          author_email: sayak.kr.dutta1@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
