name: Create Chart

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ratings-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install requests

      - name: Create Chart
        run: python codes/generate_plot.py > plot.png

      - name: Embed Chart in README
        run: |
          currentDate=$(date +'%Y-%m-%d %H:%M:%S')
          printf "\n![Chess Rating Plot](plot.png)\n\nChart last updated - ${currentDate}" >> README.md

      - name: Update workflow yaml file
        run: |
          python codes/generate_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"
          cp rating-yaml.txt .github/workflows/rating-chart.yml

      - name: Commit changes
        id: changed
        run: git diff --exit-code
        continue-on-error: true

      - name: Push changes
        if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Sayak Kumar Dutta
          author_email: sayak.kr.dutta1@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
