name: Update Readme with Chess Rating Plot
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ratings-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Plot
        run: python generate_plot.py

      - name: Convert Plot to PNG
        run: |
          python codes/convert_plot_to_png.py
          mv plot.png $GITHUB_WORKSPACE/plot.png

      - name: Embed Plot in README
        run: |
          base64 -w 0 $GITHUB_WORKSPACE/plot.png > plot_base64.txt
          echo -e "\n![Chess Rating Plot](data:image/png;base64,$(cat plot_base64.txt))" >> README.md

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with Chess Rating Plot"
          git push
        env:
          GH_TOKEN_1: ${{ secrets.GH_TOKEN_1 }}
