name: Update Readme with Chess Rating Plot
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ratings-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Plot
        run: python generate_plot.py

      - name: Move Plot to Assets
        run: |
          mkdir -p assets
          mv plot.png assets/plot.png

      - name: Update README
        run: |
          currentDate=$(date +'%Y-%m-%d %H:%M:%S')
          printf "\n![Chess Rating Plot](assets/plot.png)\n\nPlot last updated - ${currentDate}" >> README.md

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with Chess Rating Plot"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
