name: Create Chart Revision 6

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart6.yml
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Delete existing plot.png
        run: rm -f assets/plot.png
        
      - name: Create Chart
        run: python generate_plot.py > assets/plot.png
        
      - name: embed plot
        run: python plotembed.py

      - name: Check if plot.png exists
        id: check_plot
        run: |
          if [ -f "assets/plot.png" ]; then
            echo "Plot image exists."
            echo "::set-output name=plot_exists::true"
          else
            echo "Plot image does not exist."
            echo "::set-output name=plot_exists::false"
          fi

      - name: Commit and push changes
        if: steps.check_plot.outputs.plot_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/plot.png
          git commit -m "Update chess rating plot"
          git push origin main

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
