name: Update Plot

on:
  schedule:
    - cron: '0 */5 * * *' # Run every 5 hours

jobs:
  update-plot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib requests  # Install necessary Python packages

      - name: Generate plot
        run: python generate_plot.py

      - name: Update README with latest plot image
        run: python update_readme.py  # Replace this with the actual script to update README

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Update plot and README"
          git push
