name: Generate Plot Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt # if you have any dependencies, replace `requirements.txt` with the actual file name

      - name: Run script
        run: python generate_plot.py
