name: Generate Plot Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use '3.x' to specify any version of Python 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python generate_plot.py
